[package]
name = "core_library_ffi"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
core_library = { path = "../core_library" }
interoptopus = { path = "../../../crates/core" }
